In [1]:
import numpy as np

In [4]:
# 1: Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.14.5
blas_mkl_info:
  NOT AVAILABLE
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    language = c
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    language = c
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
openblas_info:
    libraries = ['openblas', 'openblas']
    language = c
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['openblas', 'openblas']
    language = c
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
None


In [9]:
# 2: Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# 3 : How to get the documentation of the numpy add function
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [12]:
# 5 : Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [14]:
# 6 : Create a vector with values ranging from 10 to 49
vec = np.arange(10, 49)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [15]:
# 7 : Reverse a vector (first element becomes last)
vec = np.arange(10)
print(vec[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [18]:
# 8: Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# 9: Find indices of non-zero elements from [1,2,0,0,4,0]
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [25]:
# 10: Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# 11: Create a 3x3x3 array with random values
matrix = np.random.random((3, 3, 3))
print(matrix)

[[[0.32777651 0.38528752 0.41182869]
  [0.31623898 0.02223183 0.40626424]
  [0.41177036 0.86298634 0.73633983]]

 [[0.52182378 0.87200934 0.69332165]
  [0.58009795 0.03601022 0.96254791]
  [0.51430506 0.91872046 0.50950557]]

 [[0.15191496 0.92555827 0.46798961]
  [0.3861286  0.97898751 0.14021307]
  [0.83427546 0.28670529 0.10049307]]]


In [37]:
# 12: Create a 10x10 array with random values and find the minimum and maximum values
matrix = np.random.random((10, 10))
print("Maximum Value : ", matrix.max())
print("Minimum Value : ", matrix.min())

Maximum Value :  0.9834844296872676
Minimum Value :  0.005793313552298618


In [39]:
# 13: Create a random vector of size 30 and find the mean value 
vec = np.random.random(30)
print("Mean of a vector : ", vec.mean())

Mean of a vector :  0.4516617273489014


In [48]:
# 14: Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
# 15 : What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [58]:
# 16: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.arange(1, 5)
print(matrix)

[1 2 3 4]


In [63]:
# 17: Create a 8x8 matrix and fill it with a checkerboard pattern
matrix = np.zeros((8,8))
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
