In [4]:
import numpy as np
import pandas as pd

In [5]:
""" Difference Between Numpy and Python Sequences
1. Numpy arrays have a fixed size at creation, unlike python lists (which can grow dynamically).Changing the size of ndarray
   will create a new array and delete the original
   
2. The elements in a Numpy array are all required to be of the same data type and thus will be the same size in memory

3. Numpy arrays are facilitate advances mathematical and other types of operations on large numbers of data. Typically such 
   operations are executed more efficiently and with less code than is possible using pythons build in sequences"""

' Difference Between Numpy and Python Sequences\n1. Numpy arrays have a fixed size at creation, unlike python lists (which can grow dynamically).Changing the size of ndarray\n   will create a new array and delete the original\n   \n2. The elements in a Numpy array are all required to be of the same data type and thus will be the same size in memory\n\n3. Numpy arrays are facilitate advances mathematical and other types of operations on large numbers of data. Typically such \n   operations are executed more efficiently and with less code than is possible using pythons build in sequences'

In [6]:
# Create a simple one-dimensional array
simple_array = np.random.randint(10, size=10)
simple_array

array([1, 9, 9, 7, 6, 9, 3, 0, 6, 6])

In [7]:
simple_array = np.arange(15).reshape(3, 5)
simple_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
"""Different Attributes of ndarray such as: shape, ndim, size, dtype, data, itemsize"""

'Different Attributes of ndarray such as: shape, ndim, size, dtype, data, itemsize'

In [9]:
# shape: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
simple_array.shape

(3, 5)

In [10]:
# ndim: the number of axes (dimensions) of the array.
simple_array.ndim

2

In [11]:
# size: the total number of elements of the array. This is equal to the product of the elements of shape.
simple_array.size

15

In [12]:
# dtype: an object describing the type of the elements in the array.
simple_array.dtype

dtype('int64')

In [13]:
# itemsize: the size in bytes of each element of the array.
simple_array.itemsize

8

In [14]:
# data:
simple_array.data

In [15]:
"""Create a array from python list"""

'Create a array from python list'

In [16]:
lst = [1, 2, 3, 4, 'a', 25.5, "Example"]
a = np.array(lst)

In [17]:
array_with_all_zeros = np.zeros((5,5))
array_with_all_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
array_with_all_ones = np.ones((3, 5))
array_with_all_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
array_with_all_empty = np.empty((3, 5))
array_with_all_empty

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# np.arange(start, stop, step)
array_with_arange = np.arange(10, 35, 5)
array_with_arange

array([10, 15, 20, 25, 30])

In [21]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [22]:
# To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.
np.set_printoptions(threshold=np.nan)

In [28]:
# SHAPE MANIPULATION IN NUMPY
array = np.random.random((3,4))
print("Shape of Array : ", array.shape)
new_arr = array.ravel()
print("New Array : ", new_arr)

Shape of Array :  (3, 4)
New Array :  [0.31487211 0.25352919 0.9815365  0.72736548 0.80833613 0.36415288
 0.47384549 0.67791398 0.5567987  0.12820051 0.94684843 0.79812953]
