In [2]:
import numpy as np

In [3]:
a = np.array([10, 20, 30, 40, 50])

In [4]:
b = np.arange(5)

In [5]:
c = a - b

In [6]:
c

array([10, 19, 28, 37, 46])

In [7]:
b**2

array([ 0,  1,  4,  9, 16])

In [8]:
10*np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [9]:
a<35

array([ True,  True,  True, False, False])

In [10]:
A = np.array([[1, 1], [0, 1]])

In [11]:
B = np.array([[2, 0], [3, 4]])

In [12]:
A * B

array([[2, 0],
       [0, 4]])

In [13]:
# To understand dot product of two matrix, please visit https://www.mathsisfun.com/algebra/matrix-multiplying.html
A @ B

array([[5, 4],
       [3, 4]])

In [14]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [28]:
# Compound Matrix Operations: Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.
a = np.ones((2,3), dtype=int)
b = np.random.random((2, 3))

In [29]:
a *=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [30]:
# please note that a's dtype is int and b's dtype is float, and here we are adding int type array to float type
b += a
b

array([[3.41149969, 3.91728249, 3.53633987],
       [3.11672369, 3.69651828, 3.07689171]])

In [33]:
# This is not possible, to add a float type array to int one
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [34]:
# When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [38]:
# Some more mathematical operations like sum, min, max, average, mean etc
a = np.random.random((2, 3))
print("Matrix : ", a)
print("Sum of a Matrix : ", a.sum())
print("Minimum value in a Matrix : ", a.min())
print("Max value in a Matrix : ", a.max())

Matrix :  [[0.77844607 0.79096393 0.38912722]
 [0.02968559 0.87701901 0.82329108]]
Sum of a Matrix :  3.6885328951761025
Minimum value in a Matrix :  0.029685591408086243
Max value in a Matrix :  0.8770190077365374


In [46]:
# Axis wise mathematical operations
b = np.arange(12).reshape(3, 4)
print("Matrix : ", b)
print("Column Wise Sum : ", b.sum(axis=0))
print("Minium Value from Each Row : ", b.min(axis=1))
print("Cumulative Sum Along Each Row : ", b.cumsum(axis=1))

Matrix :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Column Wise Sum :  [12 15 18 21]
Minium Value from Each Row :  [0 4 8]
Cumulative Sum Along Each Row :  [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
