In [1]:
import numpy as np

In [2]:
matrix = np.random.random((3, 4))

In [3]:
matrix.shape

(3, 4)

In [13]:
# Flatten the matrix
flat_matrix = matrix.ravel()
print(flat_matrix)

[0.93509024 0.9416055  0.73106219 0.17226585 0.12109589 0.79493519
 0.6302986  0.34141565 0.14255293 0.6041127  0.65840098 0.19672081]


In [14]:
reshaped_matrix = matrix.reshape(6, 2)
print(reshaped_matrix)

[[0.93509024 0.9416055 ]
 [0.73106219 0.17226585]
 [0.12109589 0.79493519]
 [0.6302986  0.34141565]
 [0.14255293 0.6041127 ]
 [0.65840098 0.19672081]]


In [16]:
# Transpose of a matrix
matrix.T

array([[0.93509024, 0.12109589, 0.14255293],
       [0.9416055 , 0.79493519, 0.6041127 ],
       [0.73106219, 0.6302986 , 0.65840098],
       [0.17226585, 0.34141565, 0.19672081]])

In [17]:
# PLEASE NOTE THAT ravel(), reshape() and Transpose T doesnt modify existing array, instead they return a new one

In [18]:
# WHERE ndarray.resize() modify the exisiting array it self

In [19]:
matrix.resize(6,2)

In [20]:
matrix.shape

(6, 2)

In [22]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
new_matrix = matrix.reshape(4, -1)
print(new_matrix)

[[0.93509024 0.9416055  0.73106219]
 [0.17226585 0.12109589 0.79493519]
 [0.6302986  0.34141565 0.14255293]
 [0.6041127  0.65840098 0.19672081]]
