In [5]:
import numpy as np

In [6]:
array1 = np.random.random((2, 3))
print(array1)

[[0.84419407 0.8569861  0.36418341]
 [0.18527306 0.7262085  0.53725405]]


In [7]:
array2 = np.random.random((2, 3))
print(array2)

[[0.89766168 0.28900957 0.14190984]
 [0.07390082 0.43317103 0.59885945]]


In [8]:
np.vstack((array1, array2))

array([[0.84419407, 0.8569861 , 0.36418341],
       [0.18527306, 0.7262085 , 0.53725405],
       [0.89766168, 0.28900957, 0.14190984],
       [0.07390082, 0.43317103, 0.59885945]])

In [9]:
np.hstack((array1, array2))

array([[0.84419407, 0.8569861 , 0.36418341, 0.89766168, 0.28900957,
        0.14190984],
       [0.18527306, 0.7262085 , 0.53725405, 0.07390082, 0.43317103,
        0.59885945]])

In [ ]:
#The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays: