In [2]:
import numpy as np

In [3]:
# Universal Functions in Numpy
# NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output

In [5]:
B = np.arange(3)

In [7]:
# Exponent
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [8]:
# Square Root
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [22]:
# Sin
np.sin(B)

array([0.        , 0.84147098, 0.90929743])

In [33]:
B = np.random.random(3)
C = np.random.random(3)
D = np.random.random(3)

In [34]:
np.add(B, C, D)

array([1.20648691, 0.35321828, 0.36021869])

In [35]:
# INDEXING, SLICING & ITERATING

In [47]:
# One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
a = np.arange(10)**3
print(a)
a[::-1]

[  0   1   8  27  64 125 216 343 512 729]


array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [48]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
def f(x,y):
    return 10*x+y

In [58]:
b = np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[2, 3])
print(b[1:, :3])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]]


In [59]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])